///////////////////////////////////////////////////////////
//  BalanceoCarga.cs
//  Implementation of the Class BalanceoCarga
//  Generated by Enterprise Architect
//  Created on:      16-sep-2009 17:40:09
//  Original author: nbortolotti
///////////////////////////////////////////////////////////




namespace Singleton {
	public class BalanceoCarga {
        public static BalanceoCarga instancia;

		protected BalanceoCarga(){

		}

		~BalanceoCarga(){

		}

		public virtual void Dispose(){

		}

        public static BalanceoCarga GetBalanceo()
        {
            if (instancia == null)
            {
                instancia = new BalanceoCarga();
            }

            return instancia;
        }

	}//end BalanceoCarga

}//end namespace Singleton