///////////////////////////////////////////////////////////
//  FactoriaAmerica.cs
//  Implementation of the Class FactoriaAmerica
//  Generated by Enterprise Architect
//  Created on:      16-sep-2009 15:44:06
//  Original author: nbortolotti
///////////////////////////////////////////////////////////




public class FactoriaAmerica : FactoriaContinente {

	public FactoriaAmerica(){

	}

	~FactoriaAmerica(){

	}

	public override void Dispose(){

	}

	public override Carnivoro CrearCarnivoro(){

		return new Lobo();
	}
    public override Hervivoro CrearHervivoro()
    {

        return new Bison();
    }

}//end FactoriaAmerica