///////////////////////////////////////////////////////////
//  Leon.cs
//  Implementation of the Class Leon
//  Generated by Enterprise Architect
//  Created on:      16-sep-2009 15:44:09
//  Original author: nbortolotti
///////////////////////////////////////////////////////////




public class Leon : Carnivoro {

	public Leon(){

	}

	~Leon(){

	}

	public override void Dispose(){

	}

	public override void Come(Hervivoro h){

	}

}//end Leon