///////////////////////////////////////////////////////////
//  PersonalJuegosBuilder.cs
//  Implementation of the Class PersonalJuegosBuilder
//  Generated by Enterprise Architect
//  Created on:      15-sep-2009 22:11:33
//  Original author: nbortolotti
///////////////////////////////////////////////////////////




using Builder;
namespace Builder {
	public class PersonalJuegosBuilder : ComputadoraBuilder {

		public PersonalJuegosBuilder(){

		}

		~PersonalJuegosBuilder(){

		}

		public override void Dispose(){

		}

        public override void ConstruirEquipo()
        {
            m_Computadora = new Computadora();
            

        }

		public override void ConstruirDisco()
        {
            m_Computadora.Partes["Disco"] = "1200rpm";
		}

		public override void ConstruirMemoria()
        {
            m_Computadora.Partes["Memoria"] = "1Gb";
		}

		public override void ConstruirMonitor()
        {
            m_Computadora.Partes["Monitor"] = "17pulgadas";
		}

	}//end PersonalJuegosBuilder

}//end namespace Builder