///////////////////////////////////////////////////////////
//  Produccion.cs
//  Implementation of the Class Produccion
//  Generated by Enterprise Architect
//  Created on:      15-sep-2009 22:11:34
//  Original author: nbortolotti
///////////////////////////////////////////////////////////




using Builder;
namespace Builder {
	public class Produccion {

		public Produccion(){

		}

		~Produccion(){

		}

		public virtual void Dispose(){

		}

		/// 
		/// <param name="objBuilder"></param>
		public void Construir(ComputadoraBuilder objBuilder)
        {
            //Director de Construcción
            objBuilder.ConstruirEquipo();
            objBuilder.ConstruirMonitor();
		}

	}//end Produccion

}//end namespace Builder