///////////////////////////////////////////////////////////
//  ElementoDibujo.cs
//  Implementation of the Class ElementoDibujo
//  Generated by Enterprise Architect
//  Created on:      16-sep-2009 16:09:38
//  Original author: nbortolotti
///////////////////////////////////////////////////////////




namespace Composite {
	public abstract class ElementoDibujo {

		protected string nombre;

		public ElementoDibujo(string nombre)
        {
            this.nombre = nombre;
		}

		~ElementoDibujo(){

		}

		public virtual void Dispose(){

		}

        public abstract void Agregar(ElementoDibujo e);

        public abstract void Borrar(ElementoDibujo e);

        public abstract void Mostrar(int indice);

	}//end ElementoDibujo

}//end namespace Composite