///////////////////////////////////////////////////////////
//  Primitiva.cs
//  Implementation of the Class Primitiva
//  Generated by Enterprise Architect
//  Created on:      16-sep-2009 16:09:39
//  Original author: nbortolotti
///////////////////////////////////////////////////////////


using System.Windows.Forms;

using Composite;
namespace Composite {
	public class Primitiva : ElementoDibujo {

		public Primitiva(string nombre):base(nombre)
        {

		}

		~Primitiva(){

		}

		public override void Dispose(){

		}

        public override void Agregar(ElementoDibujo e)
        {
            //no se puede
		}

        public override void Borrar(ElementoDibujo e)
        {
            //no se puede
		}

	

		public override void Mostrar(int indice)
        {
            MessageBox.Show("indice " + indice + " " + nombre);
		}

	}//end Primitiva

}//end namespace Composite