///////////////////////////////////////////////////////////
//  Usuario.cs
//  Implementation of the Class Usuario
//  Generated by Enterprise Architect
//  Created on:      16-sep-2009 9:02:40
//  Original author: nbortolotti
///////////////////////////////////////////////////////////




using Command;
using System.Collections;
namespace Command {
	public class Usuario {

		public Calculadora m_Calculadora = new Calculadora();
        private ArrayList comandos = new ArrayList();
        private int actual = 0;

		public Usuario(){

		}

		~Usuario(){

		}

		public virtual void Dispose(){

		}

        public void Rehacer(int nivel)
        {
            for (int i = 0; i < nivel; i++)
            {
                if (actual < comandos.Count - 1)
                {
                    Comando c = comandos[++actual] as Comando;
                    c.Hacer();
                }
            }
        }



        public void Deshacer(int nivel)
        {
            for (int i = 0; i < nivel; i++)
            {
                if (actual > 0)
                {
                    Comando c = comandos[--actual] as Comando;
                    c.Deshacer();
                }
            }
        }

		public void Calcular(char pOperador, int pOperando)
        {
            Comando c = new CalculadoraComando(m_Calculadora, pOperador, pOperando);
            c.Hacer();

            comandos.Add(c);
            actual++;
		}

	}//end Usuario

}//end namespace Command