///////////////////////////////////////////////////////////
//  Cuenta.cs
//  Implementation of the Class Cuenta
//  Generated by Enterprise Architect
//  Created on:      16-sep-2009 12:18:51
//  Original author: nbortolotti
///////////////////////////////////////////////////////////


using System.Windows.Forms;

using State;
namespace State {
	public class Cuenta {

        private string creador;

        public string Creador
        {
            get { return creador; }
            set { creador = value; }
        }

		public Estado m_Estado;

		public Cuenta(string pCreador)
        {
            this.creador = pCreador;
            m_Estado = new EstadoIntermedio(10, this) ;
		}

        public int Balance
        {
            get
            {
                return m_Estado.Balance;
            }
        }

        public Estado EstadoGeneral
        {
            get
            {
                return m_Estado;
            }
        }

		~Cuenta(){

		}

		public virtual void Dispose(){

		}

		public void Depositar(int monto)
        {
            m_Estado.Depositar(monto);
            MessageBox.Show("El valor depositado es: " + monto);
            MessageBox.Show("El balance es: " + this.Balance);
            MessageBox.Show("El Tipo es: " + this.m_Estado.GetType().Name);
		}

	}//end Cuenta

}//end namespace State