///////////////////////////////////////////////////////////
//  EstadoCritico.cs
//  Implementation of the Class EstadoCritico
//  Generated by Enterprise Architect
//  Created on:      16-sep-2009 12:18:48
//  Original author: nbortolotti
///////////////////////////////////////////////////////////




using State;
namespace State {
	public class EstadoCritico : Estado {

		public EstadoCritico(Estado e)
        {
            this.balance = e.Balance;
            this.m_Cuenta = e.m_Cuenta;
            intereses = 10;
            limiteInferior = 2;
            limiteSuperior = 50;
		}

		~EstadoCritico(){

		}

		public override void Dispose(){

		}

		public override void Depositar(int monto)
        {
            balance += monto;
            //Cambio de estado segun criterio
            if (balance > limiteSuperior)
            {
                m_Cuenta.m_Estado = new EstadoIntermedio(this);
            }
		}

	}//end EstadoCritico

}//end namespace State