///////////////////////////////////////////////////////////
//  Carnivoro.cs
//  Implementation of the Class Carnivoro
//  Generated by Enterprise Architect
//  Created on:      16-sep-2009 15:44:07
//  Original author: nbortolotti
///////////////////////////////////////////////////////////




public abstract class Carnivoro {

	public Carnivoro(){

	}

	~Carnivoro(){

	}

	public virtual void Dispose(){

	}

	public abstract void Come(Hervivoro h);
	


}//end Carnivoro