///////////////////////////////////////////////////////////
//  FactoriaContinente.cs
//  Implementation of the Class FactoriaContinente
//  Generated by Enterprise Architect
//  Created on:      16-sep-2009 15:44:05
//  Original author: nbortolotti
///////////////////////////////////////////////////////////




public abstract class FactoriaContinente {

	public FactoriaContinente(){

	}

	~FactoriaContinente(){

	}

	public virtual void Dispose(){

	}

	public abstract Carnivoro CrearCarnivoro();
    public abstract Hervivoro CrearHervivoro();

}//end FactoriaContinente