///////////////////////////////////////////////////////////
//  FactoriaAfrica.cs
//  Implementation of the Class FactoriaAfrica
//  Generated by Enterprise Architect
//  Created on:      16-sep-2009 15:44:05
//  Original author: nbortolotti
///////////////////////////////////////////////////////////




public class FactoriaAfrica : FactoriaContinente {

	public FactoriaAfrica(){

	}

	~FactoriaAfrica(){

	}

	public override void Dispose(){

	}

	public override Carnivoro CrearCarnivoro(){

		return new Leon();
	}

    public override Hervivoro CrearHervivoro()
    {

        return new Antilope();
    }

}//end FactoriaAfrica