///////////////////////////////////////////////////////////
//  Lobo.cs
//  Implementation of the Class Lobo
//  Generated by Enterprise Architect
//  Created on:      16-sep-2009 15:44:08
//  Original author: nbortolotti
///////////////////////////////////////////////////////////



using System.Windows.Forms;
public class Lobo : Carnivoro {

	public Lobo(){

	}

	~Lobo(){

	}

	public override void Dispose(){

	}

	public override void Come(Hervivoro h)
    {
        MessageBox.Show(this.GetType().Name + " come " + h.GetType().Name);
	}

}//end Lobo