///////////////////////////////////////////////////////////
//  Productos.cs
//  Implementation of the Class Productos
//  Generated by Enterprise Architect
//  Created on:      16-sep-2009 17:53:15
//  Original author: nbortolotti
///////////////////////////////////////////////////////////




using Template;
namespace Template {
	public class Productos : DataAccesObject {

		public Productos(){

		}

		~Productos(){

		}

		public override void Dispose(){

		}

        public override void Seleccionar()
        {
            //sin implementar en el ejemplo
        }

		public override void Procesar()
        {
            //sin implementar en el ejemplo
		}

		

	}//end Productos

}//end namespace Template