///////////////////////////////////////////////////////////
//  Calculadora.cs
//  Implementation of the Class Calculadora
//  Generated by Enterprise Architect
//  Created on:      16-sep-2009 9:02:39
//  Original author: nbortolotti
///////////////////////////////////////////////////////////



using System.Windows.Forms;
namespace Command {
	public class Calculadora {

		public Calculadora(){

		}

		~Calculadora(){

		}

		public virtual void Dispose(){

		}

        private int valor = 0;
		public void Operación(char pOperador, int pOperando)
        {

            switch (pOperador)
            {
                case '+': 
                    valor += pOperando; 
                    break;
                case '-': 
                    valor -= pOperando; 
                    break;
                case '*': 
                    valor *= pOperando; 
                    break;
                case '/': 
                    valor /= pOperando; 
                    break;
            }
            MessageBox.Show("El valor es: " + valor.ToString() + pOperador + pOperando.ToString());

		}

	}//end Calculadora

}//end namespace Command