///////////////////////////////////////////////////////////
//  Comando.cs
//  Implementation of the Class Comando
//  Generated by Enterprise Architect
//  Created on:      16-sep-2009 9:02:37
//  Original author: nbortolotti
///////////////////////////////////////////////////////////




namespace Command {
	public abstract class Comando {

		public Comando(){

		}

		~Comando(){

		}

		public virtual void Dispose(){

		}

		public abstract void Deshacer();

		public abstract void Hacer();

	}//end Comando

}//end namespace Command