///////////////////////////////////////////////////////////
//  Director.cs
//  Implementation of the Class Director
//  Generated by Enterprise Architect
//  Created on:      16-sep-2009 14:02:00
//  Original author: nbortolotti
///////////////////////////////////////////////////////////




using Visitor;
namespace Visitor {
	public class Director : Empleado {

		public Director():base("Nicolas",1000,30){

		}

		~Director(){

		}

		public override void Dispose(){

		}

	}//end Director

}//end namespace Visitor