///////////////////////////////////////////////////////////
//  IVisitor.cs
//  Implementation of the Interface IVisitor
//  Generated by Enterprise Architect
//  Created on:      16-sep-2009 14:02:02
//  Original author: nbortolotti
///////////////////////////////////////////////////////////




using Visitor;
namespace Visitor {
	public interface IVisitor {

		/// 
		/// <param name="e"></param>
		void Visitar(Elemento e);
	}//end IVisitor

}//end namespace Visitor