///////////////////////////////////////////////////////////
//  Presidente.cs
//  Implementation of the Class Presidente
//  Generated by Enterprise Architect
//  Created on:      16-sep-2009 14:02:01
//  Original author: nbortolotti
///////////////////////////////////////////////////////////




using Visitor;
namespace Visitor {
	public class Presidente : Empleado {

		public Presidente():base("Juan",2000,60){

		}

		~Presidente(){

		}

		public override void Dispose(){

		}

	}//end Presidente

}//end namespace Visitor