///////////////////////////////////////////////////////////
//  VisitorIngreso.cs
//  Implementation of the Class VisitorIngreso
//  Generated by Enterprise Architect
//  Created on:      16-sep-2009 14:02:03
//  Original author: nbortolotti
///////////////////////////////////////////////////////////



using System.Windows.Forms;

namespace Visitor {
	public class VisitorIngreso:IVisitor
    {

		public VisitorIngreso(){

		}

		~VisitorIngreso(){

		}

		public virtual void Dispose(){

		}
        public void Visitar(Elemento e)
        {
            Empleado objEmpleado = e as Empleado;

            objEmpleado.Ingreso = 3000;
            MessageBox.Show("Tipo " + objEmpleado.GetType().Name + " Empleado " + objEmpleado.Nombre + " Ingreso " + objEmpleado.Ingreso.ToString());

        }

	}//end VisitorIngreso

}//end namespace Visitor
