///////////////////////////////////////////////////////////
//  EstadoRelajado.cs
//  Implementation of the Class EstadoRelajado
//  Generated by Enterprise Architect
//  Created on:      16-sep-2009 12:18:49
//  Original author: nbortolotti
///////////////////////////////////////////////////////////




using State;
namespace State {
	public class EstadoRelajado : Estado {

		public EstadoRelajado(){

		}

		~EstadoRelajado(){

		}

		public override void Dispose(){

		}

		public override void Depositar(int monto)
        {
            balance += monto;
		}

	}//end EstadoRelajado

}//end namespace State