///////////////////////////////////////////////////////////
//  Estado.cs
//  Implementation of the Class Estado
//  Generated by Enterprise Architect
//  Created on:      16-sep-2009 12:18:47
//  Original author: nbortolotti
///////////////////////////////////////////////////////////




using State;
namespace State {
	public abstract class Estado {

		protected int limiteInferior;
        protected int limiteSuperior;
        protected int balance;

        public int Balance
        {
            get { return balance; }
            set { balance = value; }
        }
        protected int intereses;

		public Cuenta m_Cuenta;

		public Estado(){

		}

		~Estado(){

		}

		public virtual void Dispose(){

		}

		public abstract void Depositar(int monto);

		

	}//end Estado

}//end namespace State