///////////////////////////////////////////////////////////
//  Elemento.cs
//  Implementation of the Class Elemento
//  Generated by Enterprise Architect
//  Created on:      16-sep-2009 14:01:59
//  Original author: nbortolotti
///////////////////////////////////////////////////////////




namespace Visitor {
	public abstract class Elemento {

		public Elemento(){

		}

		~Elemento(){

		}

		public virtual void Dispose(){

		}

		public abstract void Aceptar(IVisitor visitor);

	}//end Elemento

}//end namespace Visitor