///////////////////////////////////////////////////////////
//  Empleado.cs
//  Implementation of the Class Empleado
//  Generated by Enterprise Architect
//  Created on:      16-sep-2009 14:01:59
//  Original author: nbortolotti
///////////////////////////////////////////////////////////




using Visitor;
namespace Visitor {
	public class Empleado : Elemento {

		private int diasVacaciones;
		private int ingreso;
		private string nombre;

		public Empleado(string pNombre, int pIngreso, int pVacaciones)
        {
            this.nombre = pNombre;
            this.ingreso = pIngreso;
            this.diasVacaciones = pVacaciones;
		}

		~Empleado(){

		}

		public override void Dispose(){

		}

		public override void Aceptar(IVisitor visitor)
        {
            visitor.Visitar(this);
		}

		public int DiasVacaciones{
			get{
				return diasVacaciones;
			}
			set{
				diasVacaciones = value;
			}
		}

		public int Ingreso{
			get{
				return ingreso;
			}
			set{
				ingreso = value;
			}
		}

		public string Nombre{
			get{
				return nombre;
			}
			set{
				nombre = value;
			}
		}

	}//end Empleado

}//end namespace Visitor