///////////////////////////////////////////////////////////
//  Iversor.cs
//  Implementation of the Class Iversor
//  Generated by Enterprise Architect
//  Created on:      16-sep-2009 15:04:48
//  Original author: nbortolotti
///////////////////////////////////////////////////////////


using System.Windows.Forms;

using Observer;
namespace Observer {
	public class Iversor:IInversor
    {

		private string nombre;
        private Stock m_Stock;

        public Stock Stock
        {
            get { return m_Stock; }
            set { m_Stock = value; }
        }

		public Iversor(string pNombre)
        {
            this.nombre = pNombre;

		}

		~Iversor(){

		}

		public virtual void Dispose(){

		}

        public void Actualizar(Stock s)
        {
            MessageBox.Show("Notificado: " + nombre + " " + s.Producto + " cambio precio a " + s.Precio);
        }

	}//end Iversor

}//end namespace Observer