///////////////////////////////////////////////////////////
//  Cd.cs
//  Implementation of the Class Cd
//  Generated by Enterprise Architect
//  Created on:      15-sep-2009 23:37:42
//  Original author: nbortolotti
///////////////////////////////////////////////////////////




using Decorator;
namespace Decorator {
	public class Cd : ItemVenta {

		public Cd(){

		}

		~Cd(){

		}

		public override void Dispose(){

		}

		public override void Mostrar(){

		}

	}//end Cd

}//end namespace Decorator