///////////////////////////////////////////////////////////
//  Decorador.cs
//  Implementation of the Class Decorador
//  Generated by Enterprise Architect
//  Created on:      15-sep-2009 23:37:44
//  Original author: nbortolotti
///////////////////////////////////////////////////////////




using Decorator;
namespace Decorator {
	public class Decorador : ItemVenta {

        protected ItemVenta m_ItemVenta;

		public Decorador(ItemVenta objItemVenta)
        {
            this.m_ItemVenta = objItemVenta;
		}

		~Decorador(){

		}

		public override void Dispose(){

		}

		public override void Mostrar()
        {
            m_ItemVenta.Mostrar();
		}

	}//end Decorador

}//end namespace Decorator