///////////////////////////////////////////////////////////
//  ItemVenta.cs
//  Implementation of the Class ItemVenta
//  Generated by Enterprise Architect
//  Created on:      15-sep-2009 23:37:36
//  Original author: nbortolotti
///////////////////////////////////////////////////////////




namespace Decorator {
	public abstract class ItemVenta {

		private int copias;

		public ItemVenta(){

		}

		~ItemVenta(){

		}

		public virtual void Dispose(){

		}

		public int Copias{
			get{
				return copias;
			}
			set{
				copias = value;
			}
		}

		public abstract void Mostrar();

	}//end ItemVenta

}//end namespace Decorator