///////////////////////////////////////////////////////////
//  Usuario.cs
//  Implementation of the Class Usuario
//  Generated by Enterprise Architect
//  Created on:      15-sep-2009 23:37:46
//  Original author: nbortolotti
///////////////////////////////////////////////////////////


using System.Windows.Forms;

using Decorator;
using System.Collections;
namespace Decorator {
	public class Prestable : Decorador {

        protected ArrayList prestados = new ArrayList();

		public Prestable(ItemVenta objItemVenta):base(objItemVenta)
        {

		}

        public void PrestarItem(string nombre)
        {
            prestados.Add(nombre);
            m_ItemVenta.Copias--;
        }

        ~Prestable()
        {

		}

		public override void Dispose(){

		}

		public override void Mostrar()
        {
            base.Mostrar();

            foreach (string c in prestados)
            {
                MessageBox.Show("Prestado: " + c);
            }
		}

	}//end Prestable

}//end namespace Decorator