///////////////////////////////////////////////////////////
//  Revista.cs
//  Implementation of the Class Revista
//  Generated by Enterprise Architect
//  Created on:      15-sep-2009 23:37:41
//  Original author: nbortolotti
///////////////////////////////////////////////////////////

using System.Windows.Forms;


using Decorator;
namespace Decorator {
	public class Revista : ItemVenta {

		private string editor;
		private string editorial;

		public Revista(string pEditor, string pEditorial)
        {
            this.editor = pEditor;
            this.editorial = pEditorial;
		}

		~Revista(){

		}

		public override void Dispose(){

		}

		public override void Mostrar()
        {
            MessageBox.Show("Editor: " + editor);
            MessageBox.Show("Editorial: " + editorial);
		}

	}//end Revista

}//end namespace Decorator