///////////////////////////////////////////////////////////
//  Despensa.cs
//  Implementation of the Class Despensa
//  Generated by Enterprise Architect
//  Created on:      16-sep-2009 15:04:49
//  Original author: nbortolotti
///////////////////////////////////////////////////////////




using Observer;
namespace Observer {
	public class Despensa : Stock {

		public Despensa(string producto, int precio):base(producto,precio)
        {

		}

		~Despensa(){

		}

		public override void Dispose(){

		}

	}//end Despensa

}//end namespace Observer