///////////////////////////////////////////////////////////
//  IInversor.cs
//  Implementation of the Interface IInversor
//  Generated by Enterprise Architect
//  Created on:      16-sep-2009 15:04:50
//  Original author: nbortolotti
///////////////////////////////////////////////////////////




namespace Observer {
	public interface IInversor {

		void Actualizar(Stock s);
	}//end IInversor

}//end namespace Observer