///////////////////////////////////////////////////////////
//  Compuesto.cs
//  Implementation of the Class Compuesto
//  Generated by Enterprise Architect
//  Created on:      15-sep-2009 22:53:44
//  Original author: nbortolotti
///////////////////////////////////////////////////////////



using System.Windows.Forms;

namespace Adapter {
	public class Compuesto {
        //Objetivo

		private string nombre;
		protected int pesoMolecular;

		public Compuesto(string pNombre)
        {
            nombre = pNombre;
		}

		~Compuesto(){

		}

		public virtual void Dispose(){

		}

		public virtual void Mostrar()
        {
            MessageBox.Show("Nombre: " + nombre);
		}

	}//end Compuesto

}//end namespace Adapter