///////////////////////////////////////////////////////////
//  CompuestoCompleto.cs
//  Implementation of the Class CompuestoCompleto
//  Generated by Enterprise Architect
//  Created on:      15-sep-2009 22:53:46
//  Original author: nbortolotti
///////////////////////////////////////////////////////////


using System.Windows.Forms;

using Adapter;
namespace Adapter {
	public class CompuestoCompleto : Compuesto {

		public Quimico m_Quimico;

		public CompuestoCompleto(string pNombre):base(pNombre)
        {

		}

		~CompuestoCompleto(){

		}

		public override void Dispose(){

		}

		public override void Mostrar()
        {
            //Adapta
            m_Quimico = new Quimico();
            pesoMolecular = m_Quimico.GetPesoMolecular("Agua");

            base.Mostrar();
            MessageBox.Show("Peso Molecular " + pesoMolecular);

		}

	}//end CompuestoCompleto

}//end namespace Adapter