///////////////////////////////////////////////////////////
//  Quimico.cs
//  Implementation of the Class Quimico
//  Generated by Enterprise Architect
//  Created on:      15-sep-2009 22:53:47
//  Original author: nbortolotti
///////////////////////////////////////////////////////////




namespace Adapter {
	public class Quimico {

		public Quimico(){

		}

		~Quimico(){

		}

		public virtual void Dispose(){

		}

        public int GetPesoMolecular(string compuesto)
        {
            int valor = 0;
            switch (compuesto)
            {
                case "Agua":
                    valor = 10;
                    break;
                case "Aceite":
                    valor = 50;
                    break;
                
            }

            return valor;
        }


	}//end Quimico

}//end namespace Adapter