///////////////////////////////////////////////////////////
//  Libro.cs
//  Implementation of the Class Libro
//  Generated by Enterprise Architect
//  Created on:      15-sep-2009 23:37:38
//  Original author: nbortolotti
///////////////////////////////////////////////////////////



using System.Windows.Forms;

using Decorator;
namespace Decorator {
	public class Libro : ItemVenta {

		private string autor;

		public Libro(string pAutor)
        {
            autor = pAutor;

		}

		~Libro(){

		}

		public override void Dispose(){

		}

		public override void Mostrar()
        {
            MessageBox.Show("Autor: " + autor);
		}

	}//end Libro

}//end namespace Decorator