///////////////////////////////////////////////////////////
//  Categorias.cs
//  Implementation of the Class Categorias
//  Generated by Enterprise Architect
//  Created on:      16-sep-2009 17:53:16
//  Original author: nbortolotti
///////////////////////////////////////////////////////////




using Template;
namespace Template {
	public class Categorias : DataAccesObject {

		public Categorias(){

		}

		~Categorias(){

		}

		public override void Dispose(){

		}

		public override void Procesar()
        {
            //sin implementar
		}

		public override void Seleccionar()
        {
            //sin implementar
		}

	}//end Categorias

}//end namespace Template