///////////////////////////////////////////////////////////
//  Compuesto.cs
//  Implementation of the Class Compuesto
//  Generated by Enterprise Architect
//  Created on:      16-sep-2009 16:09:41
//  Original author: nbortolotti
///////////////////////////////////////////////////////////




using Composite;
using System.Collections;
namespace Composite {
	public class Compuesto : ElementoDibujo {

		private ArrayList elementos = new ArrayList();

		public Compuesto(string nombre):base(nombre)
        {

		}

		~Compuesto(){

		}

		public override void Dispose(){

		}

        public override void Agregar(ElementoDibujo e)
        {
            elementos.Add(e);
		}

        public override void Borrar(ElementoDibujo e)
        {
            elementos.Remove(e);
		}

        public override void Mostrar(int indice)
        {
            foreach (ElementoDibujo e in elementos)
            {
                e.Mostrar(indice);
            }
		}

	}//end Compuesto

}//end namespace Composite